In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer

In [2]:
df = pd.read_csv('../../data/heart_disease.csv').select_dtypes(include=['number'])
df.head()

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
0,56.0,153.0,155.0,24.991591,7.633228,342.0,NaN,12.969246,12.387250
1,69.0,146.0,286.0,25.221799,8.744034,133.0,157.0,9.355389,19.298875
2,46.0,126.0,216.0,29.855447,4.440440,393.0,92.0,12.709873,11.230926
3,32.0,122.0,293.0,24.130477,5.249405,293.0,94.0,12.509046,5.961958
4,60.0,166.0,242.0,20.486289,7.030971,263.0,154.0,10.381259,8.153887

In [4]:
renamer = {}
for col in df.columns:
    name = input(f"Old: {col} || New: ")
    renamer[col] = name
    renamer[name] = col

Old: Age || New:  age
Old: Blood Pressure || New:  bp
Old: Cholesterol Level || New:  cholesterol
Old: BMI || New:  bmi
Old: Sleep Hours || New:  sleep
Old: Triglyceride Level || New:  triglyceride
Old: Fasting Blood Sugar || New:  fbs
Old: CRP Level || New:  crp
Old: Homocysteine Level || New:  homocysteine

In [5]:
df.rename(columns=renamer, inplace=True)
df

,age,bp,cholesterol,bmi,sleep,triglyceride,fbs,crp,homocysteine
0,56.0,153.0,155.0,24.991591,7.633228,342.0,NaN,12.969246,12.387250
1,69.0,146.0,286.0,25.221799,8.744034,133.0,157.0,9.355389,19.298875
2,46.0,126.0,216.0,29.855447,4.440440,393.0,92.0,12.709873,11.230926
3,32.0,122.0,293.0,24.130477,5.249405,293.0,94.0,12.509046,5.961958
4,60.0,166.0,242.0,20.486289,7.030971,263.0,154.0,10.381259,8.153887
...,...,...,...,...,...,...,...,...,...
9995,25.0,136.0,243.0,18.788791,6.834954,343.0,133.0,3.588814,19.132004
9996,38.0,172.0,154.0,31.856801,8.247784,377.0,83.0,2.658267,9.715709
9997,73.0,152.0,201.0,26.899911,4.436762,248.0,88.0,4.408867,9.492429
9998,23.0,142.0,299.0,34.964026,8.526329,113.0,153.0,7.215634,11.873486
9999,38.0,128.0,193.0,25.111295,5.659394,121.0,149.0,14.387810,6.208531

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           9971 non-null   float64
 1   bp            9981 non-null   float64
 2   cholesterol   9970 non-null   float64
 3   bmi           9978 non-null   float64
 4   sleep         9975 non-null   float64
 5   triglyceride  9974 non-null   float64
 6   fbs           9978 non-null   float64
 7   crp           9974 non-null   float64
 8   homocysteine  9980 non-null   float64
dtypes: float64(9)
memory usage: 703.3 KB

In [7]:
imputer = KNNImputer(n_neighbors=5)
cols = df.columns
df = imputer.fit_transform(df)
df = pd.DataFrame(df, columns=cols)
df

,age,bp,cholesterol,bmi,sleep,triglyceride,fbs,crp,homocysteine
0,56.0,153.0,155.0,24.991591,7.633228,342.0,120.8,12.969246,12.387250
1,69.0,146.0,286.0,25.221799,8.744034,133.0,157.0,9.355389,19.298875
2,46.0,126.0,216.0,29.855447,4.440440,393.0,92.0,12.709873,11.230926
3,32.0,122.0,293.0,24.130477,5.249405,293.0,94.0,12.509046,5.961958
4,60.0,166.0,242.0,20.486289,7.030971,263.0,154.0,10.381259,8.153887
...,...,...,...,...,...,...,...,...,...
9995,25.0,136.0,243.0,18.788791,6.834954,343.0,133.0,3.588814,19.132004
9996,38.0,172.0,154.0,31.856801,8.247784,377.0,83.0,2.658267,9.715709
9997,73.0,152.0,201.0,26.899911,4.436762,248.0,88.0,4.408867,9.492429
9998,23.0,142.0,299.0,34.964026,8.526329,113.0,153.0,7.215634,11.873486
9999,38.0,128.0,193.0,25.111295,5.659394,121.0,149.0,14.387810,6.208531

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           10000 non-null  float64
 1   bp            10000 non-null  float64
 2   cholesterol   10000 non-null  float64
 3   bmi           10000 non-null  float64
 4   sleep         10000 non-null  float64
 5   triglyceride  10000 non-null  float64
 6   fbs           10000 non-null  float64
 7   crp           10000 non-null  float64
 8   homocysteine  10000 non-null  float64
dtypes: float64(9)
memory usage: 703.3 KB

In [9]:
df.to_csv('../../data/cholestrol.csv')